### ISSUE TITLE
Please remove the word Bluemix from the "getting started" page graphic

### ISSUE THREAD

**Issue by RogerSnook** [ibm-cloud-docs/SecureGateway#24]

**Comment by ceciliachoi** [comment]
The issue is fixed now:
<img width="1033" alt="51dbb000-ac94-11e9-9e39-ee815eb8cf0f" src="https://user-images.githubusercontent.com/41613417/64104570-0b0acb00-cda7-11e9-8e6c-0b824a5f99ac.png">
Thank you.
