### ISSUE TITLE
 Connection #1 to destination {server} had error: SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by caiozurk** [ibm-cloud-docs/SecureGateway#26]
I'm getting this error when trying to stablish connection to a internal server.
I think this is related to the certificate unknown for the host server.

**Comment by ceciliachoi** [comment]
@caiozurk
This is like what we mentioned in [this document](https://cloud.ibm.com/docs/services/SecureGateway?topic=securegateway-troubleshooting#depth-zero)
This is the error when the SG client connect to your destination {server}, and your destination {server} is using cert chain which with the self signed root cert, you will need to upload the root cert to the [resource authentication](https://cloud.ibm.com/docs/services/SecureGateway?topic=securegateway-add-dest#cloud-or-on-prem-auth) as the CA which SG client trust.
You can verify the CA file using following command:
```
openssl s_client -CAfile <CA> -connect <target_host>:<target_port>
```

If you have questions next time:
For internal customer, please ask in the Slack channel #securegateway
For external customer, please create the ticket in the [IBM cloud ticketing system](https://cloud.ibm.com/unifiedsupport/supportcenter).
Thank you.
