### ISSUE TITLE
Typo in the graphic

### ISSUE THREAD

**Issue by susanchr** [ibm-cloud-docs/SecureGateway#29]
"Secure Gateway **Serivce**" should be ---> "Secure Gateway **Service**"
![diagramSGW](https://user-images.githubusercontent.com/22967327/93329796-5beb3700-f7e3-11ea-87a2-feda631a7216.png)

**Comment by ceciliachoi** [comment]
Thank you for reporting the issue.
We are fixing the issue now.
Thank you.
