### ISSUE TITLE
Secure Gateway - Script needs to be updated

### ISSUE THREAD

**Issue by knobutan** [ibm-cloud-docs/SecureGateway#31]
1. What are the details of the issue you're experiencing?

    The script will not work as CF stopped supporting src: process.env.CF_INSTANCE_IP
    CF team recommended to use the following method to obtain its IP address.
```
> cf ssh APPNAME
vcap@XXXX:~$ curl https://api.myip.com
{"ip":"130.198.18.239","country":"Australia","cc":"AU"}
```
2. s this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/SecureGateway?topic=SecureGateway-iptables-rules#iptables-dynamic-ips

3. Do you have a suggestion about how to resolve the issue?
Take it down for now and renew it if it worth it.

**Comment by ceciliachoi** [comment]
Resolved.
